services:
  test-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-migrations:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=test-postgres
      - DB_PORT=5432
      - DB_USER=test_user
      - DB_PASSWORD=test_password
      - DB_NAME=test_db
    command: go run ./cmd/migrate -up
    depends_on:
      test-postgres:
        condition: service_healthy

  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=test-postgres
      - DB_PORT=5432
      - DB_USER=test_user
      - DB_PASSWORD=test_password
      - DB_NAME=test_db
    depends_on:
      - test-migrations
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TEST_APP_URL=http://test-app:8080
    command: go test -v ./integration/...
    depends_on:
      test-app:
        condition: service_healthy
