name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch: # Добавляем возможность ручного запуска

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # ⚠️ Укажи нужную версию Go

      - name: Run unit tests
        run: go test ./internal/...

  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cp .env.example .env

      - name: Run Integration Tests
        run: |
          make run-integration-tests

  deploy:
    needs: [unit-tests, integration-tests]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }} # Запуск только вручную
    
    steps:
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_URL }}
